title: FC Esblanco
author:
  name: fc-esblanco
  email: info@fc-esblanco.com
description: FCエスブランコは、江戸川区小岩地区を中心に活動している少年サッカークラブです

show_excerpts: false

google_analytics: 

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:
    twitter: fcesblanco
    # github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    facebook: FC-%E3%82%A8%E3%82%B9%E3%83%96%E3%83%A9%E3%83%B3%E3%82%B3-205464673717617
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - coach.md
 - map.md
 - joinclub.md
 - privacypolicy.md
 - doc.md
 - link.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
