# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: ja
title: FC Esblanco
email: info@fc-esblanco.com
description: "FCエスブランコは、江戸川区小岩地区を中心に活動している少年サッカークラブです"
baseurl: # the subpath of your site, e.g. /blog
url: ""  # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: FC Esblanco
  twitter: fcesblanco
  facebook: fcesblanco
  picture: /assets/images/logo.png
twitter_username: fcesblanco
facebook_username: FC-エスブランコ-205464673717617
github_username:
logo: /assets/images/logo.png
google_analytics: UA-122189987-2
copyright: "FC Esblanco copyright."
search: false
search_full_content: false
search_provider:
algolia:
  application_id:
  index_name:
  search_only_api_key:
  powered_by: # true (default), false

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
remote_theme: jekyll-theme-basically-basic
#theme: jekyll-theme-basically-basic
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
#collections:
#  recipes:
#    output: true
#    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
#      read_time: true
  # _recipes
#  - scope:
#      path: "_recipes"
#      type: recipes
#    values:
#      layout: post
#      read_time: true
